### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by fulldecent** [nickoneill/thatthinginswift#10]
You recommend singletons as a static class property.

But Apple's singletons (like NSFileManager) use a function (like sharedManager) for this purpose. Is there a reason for this discrepancy?

**Comment by nickoneill** [comment]
Hey there, it's simply a matter of what's appropriate in the language. I've written my share of Objective-C singletons using `dispatch_once` in a `sharedManager` class method but we get all that functionality in Swift with a simple static property.

This is much of the original point for That Thing in Swift. Swift code shouldn't just be a translation of Objective-C code that we've written before, it should be something more suited to the intricacies of the Swift language.

**Comment by fulldecent** [comment]
Excellent, understood.

If I am understanding correctly, Apple's approach, currently, is baggage from the Objective-C conversion. But we need not copy that baggage into our new projects.

**Comment by nickoneill** [comment]
Yep, you got it :)
